// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using joel_escano_AP1_P2.DAL;

#nullable disable

namespace joel_escano_AP1_P2.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20260309234452_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("joel_escano_AP1_P2.Models.AsignacionesPuntos", b =>
                {
                    b.Property<int>("AsignacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AsignacionId"));

                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalPuntos")
                        .HasColumnType("int");

                    b.HasKey("AsignacionId");

                    b.ToTable("AsignacionesPuntos");
                });

            modelBuilder.Entity("joel_escano_AP1_P2.Models.AsignacionesPuntosDetalle", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetalleId"));

                    b.Property<int>("AsignacionId")
                        .HasColumnType("int");

                    b.Property<int>("CantidadPuntos")
                        .HasColumnType("int");

                    b.Property<int>("TipoPuntosId")
                        .HasColumnType("int");

                    b.HasKey("DetalleId");

                    b.HasIndex("AsignacionId");

                    b.ToTable("AsignacionesPuntosDetalle");
                });

            modelBuilder.Entity("joel_escano_AP1_P2.Models.Estudiantes", b =>
                {
                    b.Property<int>("EstudianteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstudianteId"));

                    b.Property<int>("BalancePuntos")
                        .HasColumnType("int");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EstudianteId");

                    b.ToTable("Estudiantes");

                    b.HasData(
                        new
                        {
                            EstudianteId = 1,
                            BalancePuntos = 0,
                            Edad = 20,
                            Email = "ana@universidad.edu",
                            Nombres = "Ana Martínez"
                        },
                        new
                        {
                            EstudianteId = 2,
                            BalancePuntos = 0,
                            Edad = 22,
                            Email = "carlos@universidad.edu",
                            Nombres = "Carlos Pérez"
                        },
                        new
                        {
                            EstudianteId = 3,
                            BalancePuntos = 0,
                            Edad = 21,
                            Email = "laura@universidad.edu",
                            Nombres = "Laura Rodríguez"
                        });
                });

            modelBuilder.Entity("joel_escano_AP1_P2.Models.TiposPuntos", b =>
                {
                    b.Property<int>("TipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ValorPuntos")
                        .HasColumnType("int");

                    b.HasKey("TipoId");

                    b.ToTable("TiposPuntos");

                    b.HasData(
                        new
                        {
                            TipoId = 1,
                            Activo = true,
                            Color = "primary",
                            Descripcion = "Participación en clase",
                            Icono = "bi-hand-thumbs-up",
                            Nombre = "Participación",
                            ValorPuntos = 5
                        },
                        new
                        {
                            TipoId = 2,
                            Activo = true,
                            Color = "success",
                            Descripcion = "Entrega de tarea",
                            Icono = "bi-journal-check",
                            Nombre = "Tarea Entregada",
                            ValorPuntos = 10
                        },
                        new
                        {
                            TipoId = 3,
                            Activo = true,
                            Color = "warning",
                            Descripcion = "Entrega de proyecto",
                            Icono = "bi-lightbulb",
                            Nombre = "Proyecto",
                            ValorPuntos = 20
                        });
                });

            modelBuilder.Entity("joel_escano_AP1_P2.Models.AsignacionesPuntosDetalle", b =>
                {
                    b.HasOne("joel_escano_AP1_P2.Models.AsignacionesPuntos", null)
                        .WithMany("AsignacionesPuntosDetalle")
                        .HasForeignKey("AsignacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("joel_escano_AP1_P2.Models.AsignacionesPuntos", b =>
                {
                    b.Navigation("AsignacionesPuntosDetalle");
                });
#pragma warning restore 612, 618
        }
    }
}
